print("This programme will help you to calculate the diameter, circumfrence and area of a circle")
print("Rule:All you need to do is to provide the radius of the circle")
radius=int(input("Provide the radius of the circle(metres):"))
print("The diameter of the circle(metres)=",2*radius,"m",sep="")
print("The circumference of the circle(metres)= ",3.14*2*radius,"m",sep="")
print('The area of the circle(metres)= ',3.14*radius**2,"m^2",sep="")